### ISSUE TITLE
Command causes undesired ui changes 

### ISSUE THREAD

**Issue by kkangs0226** [AY2021S1-CS2103T-T10-1/tp#102]
![image](https://user-images.githubusercontent.com/66008784/97271279-544f9100-186b-11eb-9363-74914f87a4b9.png)
^extra line

![image](https://user-images.githubusercontent.com/66008784/97271440-83660280-186b-11eb-9c65-d37633e99cbc.png)

^without line

Editing a project in project view or a task in task view causes a line to appear.

**Comment by kkangs0226** [comment]
A correction of my previous comment, it is not just edit command, alternating commands cause the line to appear and disappear

**Comment by boundtotheearth** [comment]
Sorry but I don't see the difference. Can you draw a big red circle around this line? (no troll i legit don't see it)

**Comment by kkangs0226** [comment]
![Screenshot 2020-10-27 at 7 35 42 PM](https://user-images.githubusercontent.com/66008784/97296585-d3ed5800-188b-11eb-8c07-fd81ef740967.png)
the line appears and disappears with alternating commands!!

![Screenshot 2020-10-27 at 7 35 50 PM](https://user-images.githubusercontent.com/66008784/97296593-d64fb200-188b-11eb-914a-327352c5d5c7.png)

**Comment by pr4aveen** [comment]
<img width="374" alt="Screenshot 2020-10-26 at 11 58 24 PM" src="https://user-images.githubusercontent.com/2839596/97296604-db146600-188b-11eb-8926-1501ea84cdc8.png">

<img width="388" alt="Screenshot 2020-10-26 at 11 58 19 PM" src="https://user-images.githubusercontent.com/2839596/97296615-dd76c000-188b-11eb-88ec-abd1c558a0f6.png">

To replicate, make sure the time spent tab isn't fully filled and run a random command like `edit 1 n/lol`
