### ISSUE TITLE
Tag pane resizes when typing in command box

### ISSUE THREAD

**Issue by claracheong4** [AY2021S1-CS2103T-T10-1/tp#112]
![image](https://user-images.githubusercontent.com/59820998/97283490-e1e6ad00-187a-11eb-92fe-75414ad3248f.png)
The command is not yet executed, enter is not pressed, just typing stuff in the command box causes the tags pane increase its height.

**Comment by boundtotheearth** [comment]
I don't have this issue. Could it be due to your changes to the reminder UI?

**Comment by claracheong4** [comment]
![image](https://user-images.githubusercontent.com/59820998/97836583-94a18a00-1d17-11eb-8a9b-c66bbae0e9c2.png)
The is a real problem. Not only the tags pane resize unexpectedly, the other panes in the sidebar resizes
