### ISSUE TITLE
Find results does not persist after edit command is executed

### ISSUE THREAD

**Issue by pr4aveen** [AY2021S1-CS2103T-T10-1/tp#63]
To replicate:

1. Filter the project list by any parameter (make sure at least 1 entry is filtered out)
2. Run the edit command on any project in the filtered list
3. The entire project list will be shown again

Is this behaviour something we should try to fix?

**Comment by kkangs0226** [comment]
Yup, I think we can try to fix this issue

**Comment by pr4aveen** [comment]
But one thing to consider is that the entry that you are working on might disappear.

Let's say your filtered list only has one entry. If you edit that entry and it the project doesn't match the predicate anymore, the list will not be empty. This might be a little weird from a UX perspective.

I'm not sure whether we should fix this. What do the rest think?
