### ISSUE TITLE
Find command only works with prefixes

### ISSUE THREAD

**Issue by kkangs0226** [AY2021S1-CS2103T-T10-1/tp#66]
Perhaps we could make it work without prefixes as well? Since users might not know whether their keywords are in description or tags, and some words could be repeated for description, name, and you might want to search for all projects with this keyword in any of the fields. 

EX) find all projects with keyword 'hello' in any field

current command: find match/any n/hello t/hello d/hello 
possible command after update: find hello (assumes match/any)

I think this might come in handy for users who are more 'lazy' and just want a simple command to filter out projects. It will also be useful when users don't recall which field the keyword goes under. What do the rest think?

**Comment by claracheong4** [comment]
So no prefix will mean match any be default?

**Comment by kkangs0226** [comment]
Yup I think that will be good

**Comment by pr4aveen** [comment]
Feature will not be implemented.
